function T = read_main_text_source_table(sheetName)
% Read a source-data table from the consolidated manuscript workbook.
%
% The workbook is generated by:
%   manuscript_figure_source_data/code/build_source_data_workbook.py

matlabDir = fileparts(mfilename('fullpath'));
dawnRoot = fullfile(matlabDir, '..', '..', '..');
workbook = fullfile(dawnRoot, 'manuscript_figure_source_data', 'data', 'main_text_source_data.xlsx');

T = readtable(workbook, 'Sheet', sheetName);
end
